version: '3'

networks:
  tk-pro-net:
    driver: bridge

services:
  astrolabe-app:
    image: registry.cn-shanghai.aliyuncs.com/leon-pu/astrolabe:1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astrolabe_app_c
    depends_on:
      - verdaccio
    networks:
      - tk-pro-net
    environment:
      - APP_KEY=taixiangtk
      - DB_DIALECT=postgres
      - DB_HOST=106.55.173.188
      - DB_PORT=9201
      - DB_DATABASE=tiktok
      - DB_USER=postgres
      - DB_PASSWORD=Leon.pu199139!
      - DB_TIMEZONE=+08:00
      - INIT_APP_LANG=zh-CN
      - DB_LOGGING=off
      - LOGGER_LEVEL=error
    volumes:
      - /var/tk/storage:/app/nocobase/storage
    ports:
      - '9900:80'
    init: true
    restart: always

  verdaccio:
    image: verdaccio/verdaccio
    container_name: verdaccio_c
    environment:
      VERDACCIO_PORT: 10104
    ports:
      - '10104:10104'
    # volumes:
    #   - ./verdaccio/conf:/verdaccio/conf
    #   - ./verdaccio/storage:/verdaccio/storage
    #   - ./verdaccio/plugins:/verdaccio/plugins
    networks:
      - tk-pro-net
    restart: always
