import { Plugin } from '@nocobase/client';
import { registerPaymentComponent } from './Payment';
import { registerSignComponent } from './Signin';
import { registerInfluencerOverviewComponent } from './InfluencerOverview';
import { registerInfluencerVideoOverviewComponent } from './InfluencerVideoOverview';
import { registerInfluencerLiveOverviewComponent } from './InfluencerLiveOverview';
import { registerInfluencerSalesOverviewComponent } from './InfluencerSalesOverview';
import { registerProductOverviewComponent } from './ProductOverview';
import { registerProductVideoOverviewComponent } from './ProductVideoOverview';
import { registerProductLiveOverviewComponent } from './ProductLiveOverview';
import { registerLiveOverviewComponent } from './LiveOverview';
import { registerSellerOverviewComponent } from './SellerOverview';
import { registerSellerVideoOverviewComponent } from './SellerVideoOvervieiw';
import { registerSellerLiveOverviewComponent } from './SellerLiveOverview';
import { registerPaidServicePermissionSettingComponent } from './PaidServicePermission';
import { registerAlipaySettingComponent } from './AlipaySetting';
import { registerOrganizationInfoComponent } from './OrganizationInfo';
import { registerTestComponent } from './test';
import { registerHashTagOverviewComponent } from './HashTagOverview';

export const registerComponents = (props: { plugin: Plugin }) => {
  registerPaymentComponent(props);
  registerSignComponent(props);
  registerInfluencerOverviewComponent(props);
  registerInfluencerVideoOverviewComponent(props);
  registerInfluencerLiveOverviewComponent(props);
  registerInfluencerSalesOverviewComponent(props);
  registerProductOverviewComponent(props);
  registerProductVideoOverviewComponent(props);
  registerProductLiveOverviewComponent(props);
  registerLiveOverviewComponent(props);
  registerSellerOverviewComponent(props);
  registerSellerVideoOverviewComponent(props);
  registerSellerLiveOverviewComponent(props);
  registerPaidServicePermissionSettingComponent(props);
  registerAlipaySettingComponent(props);
  registerOrganizationInfoComponent(props);
  registerHashTagOverviewComponent(props);
  registerTestComponent(props);
  // registerTest2Component(props);
};
